#!/bin/sh

set -e

echo "Running pre push hook!"
repository_path=$(git rev-parse --show-toplevel)

echo "Running isort.."
# Run isort for each python project
git ls-files '*.py' | xargs -I {} isort --src-path="{}" "{}"

echo "Running black.."
black "$repository_path"

echo "Running pylint.."
pylint $(git ls-files '*.py')

echo "Running mypy.."
git ls-files '*.py' | xargs --max-lines=1 mypy
